# Generated by Django 3.2.5 on 2021-07-24 02:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=100, unique=True)),
                ('desc_classe', models.TextField()),
            ],
            options={
                'verbose_name': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dept', models.CharField(max_length=200, unique=True)),
                ('nom_dept_en', models.CharField(help_text='dept name in English', max_length=200, null=True)),
                ('email_dept', models.EmailField(max_length=200, unique=True)),
                ('numero_dept', models.CharField(max_length=200, unique=True)),
                ('desc_dept', models.TextField()),
            ],
            options={
                'verbose_name': 'Departement',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('prenom', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=200, unique=True)),
                ('code_matiere', models.CharField(max_length=200, unique=True)),
                ('coef_matiere', models.IntegerField()),
                ('credit_matiere', models.IntegerField()),
                ('quota_horaire', models.IntegerField()),
                ('desc_matiere', models.TextField()),
            ],
            options={
                'verbose_name': 'Matiere',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('prenom', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='UE_matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_UE', models.CharField(max_length=100, unique=True)),
                ('code_UE', models.CharField(max_length=100, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eptSN.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UE_matieres', to='eptSN.matiere')),
            ],
            options={
                'verbose_name': 'UE_matiere',
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('prenom', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contact_prof', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='le numero de telephone est invalide!', regex='^(\\+221)?[- ]?(77|70|76|78)[- ]?([0-9]{3})[- ]?([0-9]{2}[- ]?){2}$')])),
                ('date_adhesion', models.DateField()),
                ('chef_departement', models.BooleanField(default=False)),
                ('departments', models.ManyToManyField(related_name='professeurs', to='eptSN.Departement')),
            ],
            options={
                'verbose_name': 'Professeur',
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeurs',
            field=models.ManyToManyField(related_name='matieres', to='eptSN.Professeur'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(2021)])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eptSN.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eptSN.etudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eptSN.departement'),
        ),
    ]
