# Generated by Django 3.2.5 on 2021-07-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eptSN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='annee_scolaire',
            new_name='a_scolaire',
        ),
    ]
