# Generated by Django 3.2.5 on 2021-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eptSN', '0003_rename_a_scolaire_inscription_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_naissance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
    ]
